// Generated by Tools/gen-crypto.js — do not edit by hand.
// Top coins by market cap from CoinGecko (live as of 2026-07-29); stablecoins omitted.
// Symbols fiat already claims are reserved — those coins resolve by name only.
enum CryptoData {
	/// (ticker, display name, CoinGecko id). The id is what CryptoRateStore prices.
	static let all: [(code: String, name: String, id: String)] = [
		("BTC", "Bitcoin", "bitcoin"),
		("ETH", "Ethereum", "ethereum"),
		("BNB", "BNB", "binancecoin"),
		("XRP", "XRP", "ripple"),
		("SOL", "Solana", "solana"),
		("TRX", "TRON", "tron"),
		("WBT", "WhiteBIT Coin", "whitebit"),
		("HYPE", "Hyperliquid", "hyperliquid"),
		("DOGE", "Dogecoin", "dogecoin"),
		("RAIN", "Rain", "rain"),
		("LEO", "LEO Token", "leo-token"),
		("ZEC", "Zcash", "zcash"),
		("XMR", "Monero", "monero"),
		("LINK", "Chainlink", "chainlink"),
		("ADA", "Cardano", "cardano"),
		("XLM", "Stellar", "stellar"),
		("CC", "Canton", "canton-network"),
		("BCH", "Bitcoin Cash", "bitcoin-cash"),
		("USD1", "USD1", "usd1-wlfi"),
		("GRAM", "Gram (prev. Toncoin)", "the-open-network"),
		("LTC", "Litecoin", "litecoin"),
		("USDG", "Global Dollar", "global-dollar"),
		("HBAR", "Hedera", "hedera-hashgraph"),
		("USYC", "Circle USYC", "hashnote-usyc"),
		("AVAX", "Avalanche", "avalanche-2"),
		("SUI", "Sui", "sui"),
		("SHIB", "Shiba Inu", "shiba-inu"),
		("PYUSD", "PayPal USD", "paypal-usd"),
		("BUIDL", "BlackRock USD Institutional Digital Liquidity Fund", "blackrock-usd-institutional-digital-liquidity-fund"),
		("CRO", "Cronos", "crypto-com-chain"),
		("XAUT", "Tether Gold", "tether-gold"),
		("UNI", "Uniswap", "uniswap"),
		("USDY", "Ondo US Dollar Yield", "ondo-us-dollar-yield"),
		("NEAR", "NEAR Protocol", "near"),
		("ONDO", "Ondo", "ondo-finance"),
		("TAO", "Bittensor", "bittensor"),
		("OKB", "OKB", "okb"),
		("PAXG", "PAX Gold", "pax-gold"),
		("WLFI", "World Liberty Financial", "world-liberty-financial"),
		("ASTER", "Aster", "aster-2"),
		("HTX", "HTX DAO", "htx-dao"),
		("RLUSD", "Ripple USD", "ripple-usd"),
		("USDD", "USDD", "usdd"),
		("AAVE", "Aave", "aave"),
	]

	/// Tickers the fiat table already owns (`sol` is the Peruvian sol). Fiat wins; these
	/// coins are still reachable by their full name.
	static let reservedSymbols: Set<String> = [
		"sol",
	]
}
