#!/usr/bin/env node
// Generate Tinycast/Core/Calculator/CryptoData.generated.swift.
//
// Usage: node Tools/gen-crypto.js [markets.json]
// Downloads the source when a path isn't given. Run occasionally, commit the output.
//
// CoinGecko decides which coins exist and what they're called — the same feed CryptoRateStore
// prices them from, so the table can never list a coin the app can't price. Only the top coins by
// market cap are emitted: the long tail is where ticker collisions and rug-pulls live, and a
// launcher does not need the 4,000th token.
//
// A symbol claimed by fiat wins for fiat. SOL is the live example — "sol" is already the Peruvian
// sol, so Solana is emitted with its symbol reserved and stays reachable as "solana". Picking the
// coin over the currency would be a product call, not a lookup, so this file refuses to make it.
"use strict";

const fs = require("fs");
const path = require("path");

const MARKETS =
	"https://api.coingecko.com/api/v3/coins/markets" +
	"?vs_currency=eur&order=market_cap_desc&per_page=50&page=1";

// Stablecoins track a fiat currency 1:1, so quoting them adds a rounding error and no information.
const SKIP_IDS = new Set(["tether", "usd-coin", "dai", "first-digital-usd", "usds", "ethena-usde"]);

async function load(url, argPath) {
	if (argPath) return JSON.parse(fs.readFileSync(argPath, "utf8"));
	console.log("fetching " + url.split("?")[0]);
	const response = await fetch(url);
	if (!response.ok) throw new Error(`${url} → HTTP ${response.status}`);
	return response.json();
}

/// Every ident the fiat table already claims: ISO codes, generated nouns, and the hand-decided
/// contested ones. Parsed from the committed sources so the two tables can never disagree.
function fiatIdents() {
	const root = path.resolve(__dirname, "..", "Tinycast/Core/Calculator");
	const generated = fs.readFileSync(path.join(root, "CurrencyData.generated.swift"), "utf8");
	const hand = fs.readFileSync(path.join(root, "CalcCurrency.swift"), "utf8");
	const idents = new Set();
	for (const [, code] of generated.matchAll(/\("([A-Z]{3})",/g)) idents.add(code.toLowerCase());
	for (const [, word] of generated.matchAll(/"([a-z]+)":\s*"[A-Z]{3}"/g)) idents.add(word);
	// CalcCurrency.contested — the nouns several currencies share, decided by hand.
	const contested = hand.match(/contested:\s*\[String:\s*\[String\]\]\s*=\s*\[([\s\S]*?)\n\t\]/);
	if (contested) for (const [, word] of contested[1].matchAll(/"([a-z]+)"/g)) idents.add(word);
	return idents;
}

function swiftString(value) {
	return '"' + value.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}

async function main() {
	const markets = await load(MARKETS, process.argv[2]);
	if (!Array.isArray(markets)) throw new Error("unexpected payload: " + JSON.stringify(markets).slice(0, 200));

	const fiat = fiatIdents();
	const rows = [];
	const reserved = [];
	const seen = new Set();

	for (const coin of markets) {
		if (SKIP_IDS.has(coin.id)) continue;
		const code = String(coin.symbol || "").toUpperCase();
		const name = String(coin.name || "").trim();
		if (!/^[A-Z0-9]{2,6}$/.test(code) || !name) continue;
		if (seen.has(code)) continue;
		seen.add(code);
		rows.push([code, name, coin.id]);
		// Reserved when fiat already owns the ticker, or the coin's own name is a fiat noun.
		if (fiat.has(code.toLowerCase()) || fiat.has(name.toLowerCase())) reserved.push(code);
	}

	const stamp = new Date().toISOString().slice(0, 10);
	const out = path.resolve(__dirname, "..", "Tinycast/Core/Calculator/CryptoData.generated.swift");
	fs.writeFileSync(
		out,
		"// Generated by Tools/gen-crypto.js — do not edit by hand.\n" +
			`// Top coins by market cap from CoinGecko (live as of ${stamp}); stablecoins omitted.\n` +
			"// Symbols fiat already claims are reserved — those coins resolve by name only.\n" +
			"enum CryptoData {\n" +
			"\t/// (ticker, display name, CoinGecko id). The id is what CryptoRateStore prices.\n" +
			"\tstatic let all: [(code: String, name: String, id: String)] = [\n" +
			rows
				.map(
					([c, n, i]) =>
						`\t\t(${swiftString(c)}, ${swiftString(n)}, ${swiftString(i)}),`,
				)
				.join("\n") +
			"\n\t]\n\n" +
			"\t/// Tickers the fiat table already owns (`sol` is the Peruvian sol). Fiat wins; these\n" +
			"\t/// coins are still reachable by their full name.\n" +
			"\tstatic let reservedSymbols: Set<String> = [\n" +
			(reserved.length
				? reserved.map((c) => `\t\t${swiftString(c.toLowerCase())},`).join("\n") + "\n"
				: "") +
			"\t]\n" +
			"}\n",
	);
	console.log(
		`wrote ${out} — ${rows.length} coins as of ${stamp}` +
			(reserved.length ? `, ${reserved.length} reserved (${reserved.join(", ")})` : ""),
	);
}

main().catch((e) => {
	console.error(e);
	process.exit(1);
});
